# configs/providers/crypto.yaml
providers:
  - name: crypto_ccxt
    type: crypto
    enabled: true
    connection:
      timeout: 30
      max_retries: 3
      retry_delay: 5
      pool_size: 5
      keep_alive: true
    
    # Provider-specific settings
    exchange: binance
    symbols:
      - BTC/USDT
      - ETH/USDT
      - SOL/USDT
      - BNB/USDT
    timeframe: 1h
    
    # Authentication (can also be set via environment variables)
    # env_prefix: CCXT
    # api_key: your_api_key  # Can use env var CCXT_API_KEY instead
    # api_secret: your_secret  # Can use env var CCXT_API_SECRET instead
    
    # Rate limiting
    rate_limit_requests: 10
    
    # Cache settings
    cache_duration: 300  # 5 minutes
  
  - name: crypto_ccxt_coinbase
    type: crypto
    enabled: true
    connection:
      timeout: 30
      max_retries: 3
      pool_size: 3
    
    # Provider-specific settings
    exchange: coinbase
    symbols:
      - BTC/USD
      - ETH/USD
    timeframe: 1d
    
    # Rate limiting
    rate_limit_requests: 5
    
    # Cache settings
    cache_duration: 600  # 10 minutes